# GitHub Actions workflow for destroying MCP Workshop AWS resources
name: Destroy MCP Workshop AWS Resources

on:
  workflow_dispatch:
    inputs:
      lab_number:
        description: 'Lab number to destroy'
        required: true
        default: '3'
        type: choice
        options:
          - '3'
          # Add more lab options as they become available
      aws_region:
        description: 'AWS Region to destroy resources in'
        required: true
        default: 'us-west-2'
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - eu-west-1
          - eu-central-1
          - ap-northeast-1
          - ap-southeast-1
          - ap-southeast-2
      confirmation:
        description: 'Type "destroy" to confirm deletion of AWS resources, or "destroy-all" to also delete the Terraform state bucket'
        required: true
        type: string

env:
  TF_WORKING_DIR: ${{ format('./lab0{0}-aws-cloud-deployment/terraform', inputs.lab_number) }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy' || github.event.inputs.confirmation == 'destroy-all' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Create lowercase bucket name
        run: |
          # Convert GitHub username to lowercase for S3 bucket name
          BUCKET_NAME="mcp-workshop-tf-state-$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=lab0${{ github.event.inputs.lab_number }}/terraform.tfstate" \
            -backend-config="region=${{ github.event.inputs.aws_region }}"

      - name: Clean ECR Repositories
        run: |
          echo "Cleaning ECR repositories before destroying resources..."
          # List all repositories
          REPOS=$(aws ecr describe-repositories --query 'repositories[*].repositoryName' --output text)
          
          # Loop through each repository and delete all images
          for REPO in $REPOS; do
            if [[ $REPO == mcp-* || $REPO == *-server ]]; then
              echo "Cleaning repository: $REPO"
              # Get list of image digests
              DIGESTS=$(aws ecr list-images --repository-name $REPO --query 'imageIds[*].imageDigest' --output text)
              
              if [ ! -z "$DIGESTS" ]; then
                # Delete all images in the repository
                aws ecr batch-delete-image --repository-name $REPO --image-ids $(echo $DIGESTS | sed 's/\s\+/,imageDigest=/g; s/^/imageDigest=/') || true
                echo "Images deleted from $REPO"
              else
                echo "No images found in $REPO"
              fi
            fi
          done
      
      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var="aws_region=${{ github.event.inputs.aws_region }}" -var="github_repository=${{ github.repository }}"
        continue-on-error: true
        
      - name: Force Destroy Resources if Terraform Failed
        if: ${{ failure() }}
        run: |
          echo "Terraform destroy encountered issues. Attempting to force delete resources..."
          
          # Force delete ECR repositories
          REPOS=$(aws ecr describe-repositories --query 'repositories[*].repositoryName' --output text)
          for REPO in $REPOS; do
            if [[ $REPO == mcp-* || $REPO == *-server ]]; then
              echo "Force deleting repository: $REPO"
              aws ecr delete-repository --repository-name $REPO --force || true
            fi
          done
          
          # Try Terraform destroy one more time
          cd ${{ env.TF_WORKING_DIR }}
          terraform destroy -auto-approve -var="aws_region=${{ github.event.inputs.aws_region }}" -var="github_repository=${{ github.repository }}" || true

      - name: Cleanup Confirmation
        run: |
          echo "✅ All AWS resources have been destroyed successfully."
          echo "Your AWS account should no longer incur charges for Lab 3 resources."
      
      - name: Clean up S3 bucket (optional)
        if: ${{ github.event.inputs.confirmation == 'destroy-all' }}
        run: |
          echo "Cleaning up Terraform state bucket..."
          # Empty the bucket first
          aws s3 rm s3://${{ env.BUCKET_NAME }} --recursive
          # Delete the bucket
          aws s3api delete-bucket --bucket ${{ env.BUCKET_NAME }} --region ${{ github.event.inputs.aws_region }}
          echo "S3 bucket deleted successfully."